#!/usr/bin/env bash
set -euo pipefail

TASK_FILE="${1:-}"

if [ -z "$TASK_FILE" ]; then
  echo "[ERROR] Missing task YAML path"
  exit 1
fi

case "$TASK_FILE" in
  /srv/ai-coding/tasks/*.yaml)
    ;;
  *)
    echo "[ERROR] Task file must be under /srv/ai-coding/tasks/"
    exit 1
    ;;
esac

if [ ! -f "$TASK_FILE" ]; then
  echo "[ERROR] Task file does not exist: $TASK_FILE"
  exit 1
fi

if [ -f /srv/ai-coding/config/secrets.env ]; then
  set -a
  source /srv/ai-coding/config/secrets.env
  set +a
fi

TASK_ID="$(yq -r '.task_id' "$TASK_FILE")"
REPO_URL="$(yq -r '.repo_url' "$TASK_FILE")"
BASE_BRANCH="$(yq -r '.base_branch' "$TASK_FILE")"
TARGET_BRANCH="$(yq -r '.target_branch' "$TASK_FILE")"
PR_TITLE="$(yq -r ".pr_title // \"[AI][$TASK_ID] Apply requested coding changes\"" "$TASK_FILE")"
PR_BODY="$(yq -r ".pr_body // \"Generated by OpenClaw + OpenCode worker.\"" "$TASK_FILE")"
CREATE_PR="$(yq -r '.create_pr // "true"' "$TASK_FILE")"

if [ -z "$TASK_ID" ] || [ "$TASK_ID" = "null" ]; then
  echo "[ERROR] Missing task_id in YAML"
  exit 1
fi

echo "========== AI CODING TASK START =========="
echo "Task ID: $TASK_ID"
echo "Base branch: $BASE_BRANCH"
echo "Target branch: $TARGET_BRANCH"
echo "=========================================="

/srv/ai-coding/run-ai-task.sh "$TASK_FILE"

REPO_DIR="/srv/ai-coding/workspaces/$TASK_ID/repo"
LOG_DIR="/srv/ai-coding/logs/$TASK_ID"

sudo chown -R "$USER:$USER" "$REPO_DIR" || true
git config --global --add safe.directory "$REPO_DIR" || true

cd "$REPO_DIR"

echo "========== GIT STATUS =========="
git status --short || true

echo "========== PUSH BRANCH =========="
if [[ "$REPO_URL" =~ ^https://github.com/ ]] && [ -n "${GITHUB_TOKEN:-}" ]; then
  AUTH_REPO_URL="${REPO_URL/https:\/\/github.com\//https:\/\/x-access-token:${GITHUB_TOKEN}@github.com\/}"
  git remote set-url origin "$AUTH_REPO_URL"
fi

git push -u origin "$TARGET_BRANCH"

PR_URL=""

if [ "$CREATE_PR" = "true" ]; then
  echo "========== CREATE PR =========="

  if command -v gh >/dev/null 2>&1; then
    if gh pr view "$TARGET_BRANCH" >/tmp/ai-pr-existing.txt 2>/dev/null; then
      PR_URL="$(gh pr view "$TARGET_BRANCH" --json url -q .url)"
      echo "PR already exists: $PR_URL"
    else
      PR_URL="$(gh pr create \
        --base "$BASE_BRANCH" \
        --head "$TARGET_BRANCH" \
        --title "$PR_TITLE" \
        --body "$PR_BODY")"
      echo "PR created: $PR_URL"
    fi
  else
    echo "[WARN] gh is not installed. Skipping PR creation."
  fi
fi

echo "$PR_URL" > "$LOG_DIR/pr-url.txt"

echo "========== RESULT SUMMARY =========="
echo "Task ID: $TASK_ID"
echo "Branch: $TARGET_BRANCH"
echo "PR: ${PR_URL:-not-created}"
echo ""
echo "Changed files:"
cat "$LOG_DIR/status.txt" || true
echo ""
echo "Recent commits:"
cat "$LOG_DIR/git-log.txt" || true
echo ""
echo "Diff preview:"
head -n 160 "$LOG_DIR/diff.patch" || true
echo ""
echo "========== AI CODING TASK DONE =========="
