#!/usr/bin/env bash
set -euo pipefail

TASK_FILE="${1:-}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -z "$TASK_FILE" ]; then
  echo "[ERROR] Missing task YAML path"
  exit 1
fi

case "$TASK_FILE" in
  /srv/ai-coding/tasks/*.yaml)
    ;;
  *)
    echo "[ERROR] Task file must be under /srv/ai-coding/tasks/"
    exit 1
    ;;
esac

if [ ! -f "$TASK_FILE" ]; then
  echo "[ERROR] Task file does not exist: $TASK_FILE"
  exit 1
fi

# Allow override via SECRETS_FILE, otherwise auto-discover common locations.
SECRETS_PATH="${SECRETS_FILE:-}"
if [ -z "$SECRETS_PATH" ]; then
  for candidate in "$SCRIPT_DIR/config/secrets.env" "/srv/ai-coding/config/secrets.env"; do
    if [ -f "$candidate" ]; then
      SECRETS_PATH="$candidate"
      break
    fi
  done
fi

if [ -n "$SECRETS_PATH" ] && [ -f "$SECRETS_PATH" ]; then
  set -a
  source "$SECRETS_PATH"
  set +a
fi

# 自動生成 TASK_ID（基於時間戳，避免重複）
TASK_ID="task-$(date +%Y%m%d-%H%M%S-%N | cut -c1-16)"

REPO_URL="$(yq -r '.repo_url' "$TASK_FILE")"
BASE_BRANCH="$(yq -r '.base_branch' "$TASK_FILE")"
TARGET_BRANCH="$(yq -r '.target_branch' "$TASK_FILE")"
PR_TITLE="$(yq -r ".pr_title // \"[AI][$TASK_ID] Apply requested coding changes\"" "$TASK_FILE")"
PR_BODY="$(yq -r ".pr_body // \"Generated by OpenClaw + OpenCode worker.\"" "$TASK_FILE")"
CREATE_PR="$(yq -r '.create_pr // "true"' "$TASK_FILE")"
# Prefer GITHUB_TOKEN, fallback to GH_TOKEN for GitHub HTTPS auth.
GIT_AUTH_TOKEN="${GITHUB_TOKEN:-${GH_TOKEN:-}}"

if [ -z "$REPO_URL" ] || [ "$REPO_URL" = "null" ]; then
  echo "[ERROR] repo_url is required"
  exit 1
fi

echo "========== AI CODING TASK START =========="
echo "Task ID: $TASK_ID"
echo "Base branch: $BASE_BRANCH"
echo "Target branch: $TARGET_BRANCH"
echo "=========================================="

/srv/ai-coding/run-ai-task.sh "$TASK_FILE"

REPO_DIR="/srv/ai-coding/workspaces/$TASK_ID/repo"
LOG_DIR="/srv/ai-coding/logs/$TASK_ID"

# Use non-interactive sudo for automation; if unavailable, continue.
sudo -n chown -R "$USER:$USER" "$REPO_DIR" || true
git config --global --add safe.directory "$REPO_DIR" || true

cd "$REPO_DIR"

echo "========== GIT STATUS =========="
git status --short || true

echo "========== PUSH BRANCH =========="
# Disable any interactive credential prompt in automation.
export GIT_TERMINAL_PROMPT=0

if [[ "$REPO_URL" =~ ^https://github.com/ ]]; then
  if [ -z "$GIT_AUTH_TOKEN" ]; then
    echo "[ERROR] Missing GitHub token. Set GITHUB_TOKEN or GH_TOKEN in config/secrets.env, /srv/ai-coding/config/secrets.env, or SECRETS_FILE."
    exit 1
  fi

  AUTH_REPO_URL="${REPO_URL/https:\/\/github.com\//https:\/\/x-access-token:${GIT_AUTH_TOKEN}@github.com\/}"
  git remote set-url origin "$AUTH_REPO_URL"
  # Ensure gh CLI can also reuse the same token during PR steps.
  export GH_TOKEN="$GIT_AUTH_TOKEN"
fi

# Sync with remote target branch when it already exists to avoid non-fast-forward push failures.
git fetch origin "$TARGET_BRANCH" || true
if git show-ref --verify --quiet "refs/remotes/origin/$TARGET_BRANCH"; then
  git rebase "origin/$TARGET_BRANCH"
fi

git push -u origin "$TARGET_BRANCH"

PR_URL=""

if [ "$CREATE_PR" = "true" ]; then
  echo "========== CREATE PR =========="

  if command -v gh >/dev/null 2>&1; then
    if gh pr view "$TARGET_BRANCH" >/tmp/ai-pr-existing.txt 2>/dev/null; then
      PR_URL="$(gh pr view "$TARGET_BRANCH" --json url -q .url)"
      echo "PR already exists: $PR_URL"
    else
      PR_URL="$(gh pr create \
        --base "$BASE_BRANCH" \
        --head "$TARGET_BRANCH" \
        --title "$PR_TITLE" \
        --body "$PR_BODY")"
      echo "PR created: $PR_URL"
    fi
  else
    echo "[WARN] gh is not installed. Skipping PR creation."
  fi
fi

echo "$PR_URL" > "$LOG_DIR/pr-url.txt"

echo "========== RESULT SUMMARY =========="
echo "Task ID: $TASK_ID"
echo "Branch: $TARGET_BRANCH"
echo "PR: ${PR_URL:-not-created}"
echo ""
echo "Changed files:"
cat "$LOG_DIR/status.txt" || true
echo ""
echo "Recent commits:"
cat "$LOG_DIR/git-log.txt" || true
echo ""
echo "Diff preview:"
head -n 160 "$LOG_DIR/diff.patch" || true
echo ""
echo "========== AI CODING TASK DONE =========="
